# Generated by Django 4.2.1 on 2024-04-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='painter',
            name='biography',
            field=models.TextField(default=None),
        ),
    ]
